name: Build and Deploy Docker Image
on: 
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker
      run: | 
          sudo apt-get update
          sudo apt-get install -y docker.io   

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mannu121/testrepo:latest

    - name: Deploy to Container
      run: |
        docker run -d --name workflow-test-image -p 80:80 mannu121/testrepo:latest
