name: Trigger Dispatch Event

# This workflow is triggered when there is a push to the main branch.
on:
  push:
    branches:
      - main

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Trigger the repository dispatch event
      - name: Trigger repository dispatch
        uses: actions/github-script@v6
        with:
          script: |
            await github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'custom-event'  # This is the custom event type
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
